language: python
python:
  - "3.7.8"
install:
  - pip install pip==10.0.1
  - pip -V
  - pip install -r src/lambda_handler/requirements.txt
script:
  - export PYTHONPATH=./src/lambda_handler
  - pytest --tb=short
